### ISSUE TITLE
Physics Asset

### ISSUE THREAD

**Issue by CyberWolf755** [Allar/ue4-style-guide#26]
It's simpler for the Physics Asset prefix to be **PA_** instead of **PHYS_** as you always mention the object as a Physics Asset and not just Physics. Also **PA_** is easier to write and shorter keeping the length of the files name 2 characters shorter. Which in my case means better and more readable :)

**Comment by Allar** [comment]
This does make a lot of sense. PHYS_ was chosen more due to a legacy reason of that Physics Assets used to be auto-created with the PHYS_ prefix or with a name that was easy to change to PHYS_, and it was easier to accept this fact than to make people go out of their way to use something like PA_.

PHYS_ is an old long term standing practice that many developers have been using, and I'm unsure if I want to be progressive here or stick to a practice with precedent.

It makes a lot of sense for people to fork and use PA_ however.
