### ISSUE TITLE
Missing Texture Suffix for Metallic

### ISSUE THREAD

**Issue by drichardson** [Allar/ue4-style-guide#32]
The current set of texture suffixes do not include a definition for the Metallic channel.

Since M is taken by Mask and the suffix needs to be a single identifier to support stacking, and there are no great synonyms for metal  I propose the suffix C, since metal conducts and is also not taken by the other texture issue #25.

Really I don't care what the suffix is, just want to standardize something. I don't have access to many existing projects, so if a suffix already exists lets use that instead.

**Comment by Allar** [comment]
This sounds crazy but I think it'd be better to use M for both metallic and mask. The difference between them is usually pretty visually obvious as well as masks/metallics are often combined with other channel data, and using M for metallic makes making things like _RMA (roughness, metallic, alpha or etc) whereas Masks are pretty general purpose and maybe it makes sense to name a mask descriptive to what that mask is actually doing.

**Comment by DeadlyMidnight** [comment]
I would have to agree with alar on this it should be self explanatory on visual inspection and masks are pretty distinct. Conductive is also a really abstract that will likely lead to confusion as it has no real bearing on the descriptive nature of the material. 

If anything masks could be denoted with A since they are effectively just alphas.

**Comment by drichardson** [comment]
I agree. _C is not intuitive. I picked it to not conflict with anything else. I'll change the pull request to make it _M.
